
[2021-04-09 14:04:06] Traceback (most recent call last):
  File "v8function_handler.pyx", line 48, in cefpython_py37.V8FunctionHandler_Execute
  File "/media/feodoritiy/HDD/CODE/VS_C+/fti/Cursach/client/logic/register.py", line 16, in register
    res = json.loads(res.text)
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)


[2021-04-09 23:53:30] Traceback (most recent call last):
  File "v8function_handler.pyx", line 48, in cefpython_py37.V8FunctionHandler_Execute
  File "/media/feodoritiy/HDD/CODE/VS_C+/fti/Cursach/client/logic/register.py", line 19, in register
    return res.status
AttributeError: 'dict' object has no attribute 'status'


[2021-04-10 00:50:28] Traceback (most recent call last):
  File "v8function_handler.pyx", line 48, in cefpython_py37.V8FunctionHandler_Execute
  File "/media/feodoritiy/HDD/CODE/VS_C+/fti/Cursach/client/logic/register.py", line 21, in register
    storage.id = res['id']
NameError: name 'storage' is not defined


[2021-04-10 01:29:01] Traceback (most recent call last):
  File "v8function_handler.pyx", line 48, in cefpython_py37.V8FunctionHandler_Execute
  File "/media/feodoritiy/HDD/CODE/VS_C+/fti/Cursach/client/logic/login.py", line 17, in login
    res = json.loads(res.text)
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)


[2021-04-10 01:30:08] Traceback (most recent call last):
  File "v8function_handler.pyx", line 48, in cefpython_py37.V8FunctionHandler_Execute
  File "/media/feodoritiy/HDD/CODE/VS_C+/fti/Cursach/client/logic/login.py", line 17, in login
    res = json.loads(res.text)
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)


[2021-04-10 01:32:01] Traceback (most recent call last):
  File "v8function_handler.pyx", line 48, in cefpython_py37.V8FunctionHandler_Execute
  File "/media/feodoritiy/HDD/CODE/VS_C+/fti/Cursach/client/logic/login.py", line 17, in login
    res = json.loads(res.text)
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)


[2021-04-10 01:33:08] Traceback (most recent call last):
  File "v8function_handler.pyx", line 48, in cefpython_py37.V8FunctionHandler_Execute
  File "/media/feodoritiy/HDD/CODE/VS_C+/fti/Cursach/client/logic/login.py", line 17, in login
    res = json.loads(res.text)
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)


[2021-04-10 01:34:28] Traceback (most recent call last):
  File "v8function_handler.pyx", line 48, in cefpython_py37.V8FunctionHandler_Execute
  File "/media/feodoritiy/HDD/CODE/VS_C+/fti/Cursach/client/logic/login.py", line 17, in login
    res = json.loads(res.text)
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)


[2021-04-11 23:10:19] Traceback (most recent call last):
  File "v8function_handler.pyx", line 48, in cefpython_py37.V8FunctionHandler_Execute
  File "/media/feodoritiy/HDD/CODE/VS_C+/fti/Cursach/client/logic/shop.py", line 20, in get_shop
    'id': storage.id,
TypeError: 'cefpython_py37.JavascriptCallback' object is not callable


[2021-04-12 00:29:32] Traceback (most recent call last):
  File "v8function_handler.pyx", line 48, in cefpython_py37.V8FunctionHandler_Execute
  File "/media/feodoritiy/HDD/CODE/VS_C+/fti/Cursach/client/logic/shop.py", line 22, in get_shop
    'shop': res.shop,
AttributeError: 'dict' object has no attribute 'shop'

